name: gradle-preview-ci
on:
  push:
    branches: [ "dev/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/*\/dev/}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.vars.outputs.version }}-SNAPSHOT"
          prerelease: true
          title: "Development Build (${{ steps.vars.outputs.version }})"
          files: |
            api/build/libs/*.jar
            platforms/*/build/libs/*(.jar|!(*-dev.jar*))